Sprint 10
DDENNEDD/ImageFeed-iOS pull request #5
Opened 2023-03-06 16:41 UTC by DDENNEDD

Задание по 10-му спринту

2023-03-07 15:49 UTC, protos17 requested changes

2023-03-07 15:49 UTC, protos17 commented on ImageFeed/AppDelegate.swift
>          // sleep(3)
Рекомендую удалить лишний закомментированный код

2023-03-07 15:49 UTC, protos17 commented on ImageFeed/Auth/AuthViewController.swift
> +            else { fatalError("Failed to prepare for \(showWebViewSegueIdentifier)") }
По своему опыту хотел бы отметить, что в продакшене не используют fatalError, советую заменить на assertionFailure.

2023-03-07 15:49 UTC, protos17 commented on ImageFeed/Auth/OAuth2/OAuth2TokenStorage.swift
> +            UserDefaults.standard.set(newToken, forKey: "bearerToken")
Ключи рекомендую вынести в приватную константу в этом же классе

2023-03-07 15:49 UTC, protos17 commented on ImageFeed/Auth/WebViewViewController.swift
> +    static let UnsplashAuthorizeURLString = "https://unsplash.com/oauth/authorize"
Константы принято писать с маленькой буквы, рекомендую поправить

2023-03-07 15:49 UTC, protos17 commented on ImageFeed/Auth/WebViewViewController.swift
> +    @IBAction func didTapBackButton(_ sender: Any?) {
Здесь стоит добавить `private`
Необходимо указывать private  для того, чтобы спрятать детали реализации конкретной части функциональности, 
когда они используются только внутри области объявления.

2023-03-07 15:49 UTC, protos17 commented on ImageFeed/SplashView/SplashViewController.swift
> +        if let token = oauth2TokenStorage.token {
Лишняя константа token, нигде не используется, можно заменить проверкой на nil

2023-03-07 15:49 UTC, protos17 commented on ImageFeed/SplashView/SplashViewController.swift
> +        guard let window = UIApplication.shared.windows.first else { fatalError("Invalid Configuration") }
По своему опыту хотел бы отметить, что в продакшене не используют fatalError, советую заменить на assertionFailure.

2023-03-07 15:49 UTC, protos17 commented on ImageFeed/SplashView/SplashViewController.swift
> +            else { fatalError("Failed to prepare for \(showAuthenticationScreenSegueIdentifier)") }
По своему опыту хотел бы отметить, что в продакшене не используют fatalError, советую заменить на assertionFailure.

2023-03-09 09:48 UTC, DDENNEDD commented on ImageFeed/AppDelegate.swift
>          // sleep(3)
удалил

2023-03-09 09:50 UTC, DDENNEDD commented on ImageFeed/Auth/WebViewViewController.swift
> +    @IBAction func didTapBackButton(_ sender: Any?) {
исправил

2023-03-09 09:51 UTC, DDENNEDD commented on ImageFeed/SplashView/SplashViewController.swift
> +        if let token = oauth2TokenStorage.token {
исправил

2023-03-09 10:02 UTC, DDENNEDD commented on ImageFeed/Auth/WebViewViewController.swift
> +    static let UnsplashAuthorizeURLString = "https://unsplash.com/oauth/authorize"
исправил

2023-03-09 13:07 UTC, DDENNEDD commented on ImageFeed/SplashView/SplashViewController.swift
> +            else { fatalError("Failed to prepare for \(showAuthenticationScreenSegueIdentifier)") }
Принял, пока не исправлял

2023-03-09 13:07 UTC, DDENNEDD commented on ImageFeed/SplashView/SplashViewController.swift
> +        guard let window = UIApplication.shared.windows.first else { fatalError("Invalid Configuration") }
Принял, пока не исправлял

2023-03-09 13:07 UTC, DDENNEDD commented on ImageFeed/Auth/OAuth2/OAuth2TokenStorage.swift
> +            UserDefaults.standard.set(newToken, forKey: "bearerToken")
Принял, пока не исправлял

2023-03-09 13:12 UTC, DDENNEDD commented
Критические:
1.
"""Приложение падает при выборе вкладки профиля (пункт 1). Связано это с неправильным написанием цвета, у тебя в Assets "white" написан с маленькой буквы, в то время как в extension UIColor у тебя все цвета написаны с большой буквы.""" 
Странная ситуация - у меня и в UIColor Ext и в Assets все названия с большой буквы, приложение не вылетает.
Остальные:
1. Кнопка - исправлено
2. Элемент таб - исправлено
3. Исправлено частично - не удалось победить на сплешскрине
Для размышлений:
1. Скорее всего исправлено - изменены констрейнты вебвью.

2023-03-09 13:26 UTC, DDENNEDD commented on ImageFeed/Auth/AuthViewController.swift
> +            else { fatalError("Failed to prepare for \(showWebViewSegueIdentifier)") }
Принял, пока не исправлял

2023-03-10 07:20 UTC, protos17 requested changes

2023-03-10 07:20 UTC, protos17 commented on ImageFeed/Helpers/Constants.swift
> +let BaseURL = URL(string: "https://unsplash.com")!
Константы принято писать с маленькой буквы, рекомендую поправить

2023-03-10 20:26 UTC, DDENNEDD commented
По замечаниям 
====Критические====
""""1.Приложение падает при выборе вкладки профиля (пункт 1). Связано это с неправильным написанием цвета, у тебя в Assets "white" и "whiteAlpha" написаны с маленькой буквы, в то время как в extension UIColor у тебя все цвета написаны с большой буквы. Остальные цвета написаны с большой буквы. Рекомендую удалить и заново добавить данные цвета, подписав их с большой буквы или в extension UIColor написать эти цвета с маленькой буквы. Для проверки, что все работает корректно, рекомендую скачать эту ветку с github и запустить её. """"
Удалил и заново добавив цвета, проблемы не наблюдаю.
====Рекомендации, не влияющие на результат проверки работы====
""""1. При нажатии на ячейку, она выделяется серым. Выделение стоит убрать. Рекомендую использовать cell.selectionStyle = .none""""
исправил согласно рекомендации.

2023-03-11 11:20 UTC, protos17 approved these changes

2023-03-11 14:32 UTC, merged